### ISSUE TITLE
Minio Browser UI to expose AWS buckets 

### ISSUE THREAD

**Issue by machbio** [minio/miniobrowser#163]
Minio Browser is currently browser that exposes only the local filesystem that the Minio Server is running, it would be amazing; if there are changes to the Minio Browser to utilize the Minio Command line application configuration to expose the AWS buckets and Google Storage.

**Comment by harshavardhana** [comment]
> Minio Browser is currently browser that exposes only the local filesystem that the Minio Server is running, it would be amazing; if there are changes to the Minio Browser to utilize the Minio Command line application configuration to expose the AWS buckets and Google Storage.

After discussing this internally there is no easier way to do this, because the scope of Minio Browser cannot go out of Minio Server's context.  Minio Browser and Minio Server are tightly coupled together using JSON RPC for API operations.  

On the other hand `mc` is meant to be used for these purposes.

**Comment by machbio** [comment]
Thank you, I understand.
